# Generated by Django 4.0.5 on 2022-06-26 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='ExpectedOutput',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='testcase',
            name='Input',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), default=list, size=None),
        ),
    ]
