# Generated by Django 4.0.5 on 2022-06-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJapp', '0002_questions_questiontitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='question',
        ),
    ]
