# Generated by Django 4.0.5 on 2022-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJapp', '0004_alter_testcase_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='Input',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
