# Generated by Django 4.0.5 on 2022-07-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJapp', '0005_alter_testcase_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test',
            field=models.CharField(choices=[('a', 'a')], max_length=200, null=True),
        ),
    ]
